### ISSUE TITLE
Refactor getQueryParameters() to use URL/URLSearchParams

### ISSUE THREAD

**Issue by shaedrich** [ponylang/pony-playground#218]
Would it make sense to refactor `getQueryParameters()` to use [`URL`](https://developer.mozilla.org/en-US/docs/Web/API/URL)/[`URLSearchParams`](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams), so we don't have to maintain custom code over native one or do you prefer not to fix something that ain't broken?
https://github.com/ponylang/pony-playground/blob/35f1d18f4706a016c913ec05bfeddcda16589c78/static/web.js#L295-L305

By the way, this
https://github.com/ponylang/pony-playground/blob/35f1d18f4706a016c913ec05bfeddcda16589c78/static/web.js#L7-L12
could also be rewritten as
```javascript
function optionalLocalStorageGetItem(key) {
    return localStorage.getItem(key) ?? null;
}
```
and so can
https://github.com/ponylang/pony-playground/blob/35f1d18f4706a016c913ec05bfeddcda16589c78/static/web.js#L496-L501
as 

```javascript
theme = optionalLocalStorageGetItem("theme");
set_theme(editor, themelist, theme ?? "GitHub");
```

as well as
https://github.com/ponylang/pony-playground/blob/35f1d18f4706a016c913ec05bfeddcda16589c78/static/web.js#L25-L33
which can be shortened to

```javascript
var themes = themelist.themes;
themes.sort((a, b) => a.caption.localeCompare(b.caption));
```

Then, we have
https://github.com/ponylang/pony-playground/blob/35f1d18f4706a016c913ec05bfeddcda16589c78/static/web.js#L116-L121
which doesn't need the `else`, since it has a `return`:
```javascript
var classes = mappings[arguments[1]];
if (classes) {
    return '<span class="' + classes + '">' + arguments[2] + '</span>';
}
return arguments[2];
```

The following is an interesting case:
https://github.com/ponylang/pony-playground/blob/35f1d18f4706a016c913ec05bfeddcda16589c78/static/web.js#L251-L258

it could either be rewritten as
```javascript
if (req.status == expect) {
    if (on_success) {
        on_success(req.responseText);
    }
} else if (on_fail) {
    on_fail(req.status, req.responseText);
}
```
or
```javascript
if (req.status == expect && on_success) {
    on_success(req.responseText);
}
if (req.status != expect && on_fail) {
    on_fail(req.status, req.responseText);
}
```

Next, we have a bunch of these:
https://github.com/ponylang/pony-playground/blob/35f1d18f4706a016c913ec05bfeddcda16589c78/static/web.js#L617-L627
when they only contain a single function call, instead of creating a bunch of overhead with new anonymous wrapper functions, you could use [`bind`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind):
```javascript
asmButton.onclick = compile.bind(window, "asm", result, session.getValue(), asmButton);

irButton.onclick = compile.bind(window, "llvm-ir", result, session.getValue(), irButton);

gistButton.onclick = shareGist.bind(window, result, session.getValue(), gistButton);

clearResultButton.onclick = clear_result.bind(window, result);

themes.onkeyup = themes.onchange = set_theme.bind(window, editor, themelist, themes.options[themes.selectedIndex].text);

request.ontimeout = set_result.bind(window, result, "<p class=error>Connection timed out" +
                "<p class=error-explanation>Are you connected to the Internet?");
```

One could possibly also refactor [`editGo()`](https://github.com/ponylang/pony-playground/blob/35f1d18f4706a016c913ec05bfeddcda16589c78/static/web.js#L653-L660), [`editShowRegion()`](https://github.com/ponylang/pony-playground/blob/35f1d18f4706a016c913ec05bfeddcda16589c78/static/web.js#L679-L687), [`editShowLine()`](https://github.com/ponylang/pony-playground/blob/35f1d18f4706a016c913ec05bfeddcda16589c78/static/web.js#L689-L698), and [`editShowPoint()`](https://github.com/ponylang/pony-playground/blob/35f1d18f4706a016c913ec05bfeddcda16589c78/static/web.js#L700C-L709), but that'd be slightly more than a simplification.

# Miscellaneous
* [`className`](https://developer.mozilla.org/en-US/docs/Web/API/Element/className) vs [`classList`](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList)
* [`fetch`](https://developer.mozilla.org/en-US/docs/Web/API/fetch) vs [`XMLHttpRequest`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest)
* [`setAttribute('data-*')`](https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttribute) vs [`dataset`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset)
* [`onclick`](https://developer.mozilla.org/en-US/docs/Web/API/Element/click_event) vs [`addEventListener()`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener)

**Comment by mfelsche** [comment]
@jemc we didnt update it from the original codebase for ages. I didnt do any work on the frontend bits, but would be happy to get those on stable feet. Happy for every improvement here.

**Comment by shaedrich** [comment]
Am I missing something or is `samples` obsolete and can be removed?
https://github.com/ponylang/pony-playground/blob/14abb9e0a3a93e0a8a33573a35fad7842dfe1ba7/static/web.js#L5

**Comment by mfelsche** [comment]
It doesn't seem to be referenced. Your js language server of choice might know more through some static analysis.

**Comment by shaedrich** [comment]
Would you like to have JSDoc comments above your functions?

**Comment by mfelsche** [comment]
Those aren't my functions. They belong to everyone. Treat them like they are yours. Whatever improves code quality, Iwe are happy to accept. I can write Rust and Pony, but I don't really dare to touch javascript.
So I hereby hand ownership of the JS code in here to you. It is old and hungry and copied and only slightly adapted from the rust playground it was forked from. Feel free to improve in any way you deem helpful (mostly to you doing further improvements).
