### ISSUE TITLE
Syntax highlighting doesn't work with annotations

### ISSUE THREAD

**Issue by shaedrich** [ponylang/pony-playground#226]
Without:
![grafik](https://github.com/ponylang/pony-playground/assets/11225821/2d401090-0b43-4000-9ddd-37aa6ee703a3)

With:
![grafik](https://github.com/ponylang/pony-playground/assets/11225821/7c359762-ded7-40b4-917d-5c699e60b9b6)

**Comment by SeanTAllen** [comment]
Yup. This is a known issue that would need to be fixed in the highlighter. I think it's pygments but I can't remember. 

The repo for the highlighter which is a 3rd party project is where it needs to be addressed.

**Comment by shaedrich** [comment]
Done: https://github.com/pygments/pygments/issues/2722

**Comment by SeanTAllen** [comment]
Closing in favor of that PR on pygments.
